name: flutter_app
description: "A new Flutter app."
publish_to: none

version: 0.0.3

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  markdown_editor_mobile_web:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.18+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
