name: markdown_editor_mobile_web
description: "A flexible and easily decoratable Markdown editor designed for Flutter."
homepage: https://github.com/feliperfdev/markdown-editor

platforms:
  android:
  ios:
  web:

topics:
  - markdown

version: 0.0.3+hotfix.rdm

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/screenshots/
